### ISSUE TITLE
Low-priority improvements

### ISSUE THREAD

**Issue by SergeyCherepanov** [SergeyCherepanov/dev-env-osx#1]
- [x] coreutils, 
- [ ] autossh, 
- [ ] cloc, 
- [ ] links,
- [ ] lynx, 
- [ ] nmap, 
- [ ] siege,
- [x] p7zip, 
- [ ] pstree, 
- [ ] unrar, 
- [ ] sqlite, 
- [ ] webkit2png, 
- [ ] xz
- [ ] ipcalc
- [ ] sipcalc
- [ ] socat

**Comment by anderles** [comment]
Great
Please add swagger too
